FROM rnakato/singlecell_jupyter:1.2.0
LABEL maintainer "Ryuichiro Nakato <rnakato@iam.u-tokyo.ac.jp>"

USER root
WORKDIR /opt

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    libgmp3-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip install -U pip

# Palantir, MAGIC
RUN pip install PhenoGraph palantir rpy2 magic-impute \
    && R -e "install.packages('gam')"

# Scrublet
RUN pip install scrublet

# SingleCellNet
RUN R -e "devtools::install_github(c('pcahan1/singleCellNet'))"
RUN R -e "devtools::install_github('mojaveazure/loomR', ref = 'develop')"

# FlyATACAtlus
RUN R -e "install.packages(c('irlba','DDRTree','densityClust'))"

# Splatter
RUN R -e "BiocManager::install('splatter')"

# SCRABBLE
RUN R -e "devtools::install_github('software-github/SCRABBLE/R')"

# Imputation comparison
RUN R -e "install.packages(c('SAVER','ClusterR'))"

# SingleCellSingnalR
RUN R -e "devtools::install_github('SCA-IRCM/SingleCellSignalR_v1', subdir = 'SingleCellSignalR')"

# Theis_Tutorial
RUN pip install gprofiler-official anndata2ri bbknn \
	&&  R -e "BiocManager::install(c('MAST','clusterExperiment'))"

# DoubletFinder
RUN R -e "devtools::install_github('chris-mcginnis-ucsf/DoubletFinder')"

# scater-cellassign
RUN R -e "install.packages(c('here'))"
RUN R -e "devtools::install_github('Irrationone/cellassign')"

# scVI
RUN conda install scvi -c bioconda -c conda-forge \
    && pip install scikit-misc plotnine

# scGen
RUN pip install scgen

# metacells
RUN R -e "BiocManager::install('metacell',  site_repository = 'tanaylab.github.io/repo', update = FALSE)"

# LIGER
RUN R -e "devtools::install_github(c('MacoskoLab/liger'))"
ADD bedops_linux_x86_64-v2.4.39 bedops_linux_x86_64-v2.4.39
ENV PATH ${PATH}:/opt/bedops_linux_x86_64-v2.4.39

# Harmony
RUN R -e "install.packages('gganimate')" \
    && R -e "BiocManager::install(c('sva','DESeq2'))" \
    && R -e "devtools::install_github(c('immunogenomics/harmony','immunogenomics/presto','JEFworks/MUDAN'))"
RUN pip install harmonypy

# Seurat wrappers
RUN R -e "BiocManager::install(c('CoGAPS'))"
RUN R -e "BiocManager::install(c('scry'))"
RUN R -e "install.packages('glmpca')"
RUN R -e "devtools::install_github('hms-dbmi/conos')"
RUN R -e "devtools::install_github('satijalab/seurat', ref = 'mixscape')"
RUN R -e "devtools::install_github('satijalab/seurat-wrappers')"
RUN R -e "devtools::install_github('satijalab/seurat-data', ref = 'develop')"
#RUN R -e "SeuratData::InstallData(c('pbmcsca','ifnb','panc8','pbmc3k'))"

COPY SeuratData/ifnb.SeuratData_3.1.0.tar.gz ifnb.SeuratData_3.1.0.tar.gz
COPY SeuratData/panc8.SeuratData_3.0.2.tar.gz panc8.SeuratData_3.0.2.tar.gz
COPY SeuratData/pbmcsca.SeuratData_3.0.0.tar.gz pbmcsca.SeuratData_3.0.0.tar.gz
COPY SeuratData/pbmc3k.SeuratData_3.0.0.tar.gz pbmc3k.SeuratData_3.0.0.tar.gz
RUN R -e "install.packages('ifnb.SeuratData_3.1.0.tar.gz', repos = NULL, type = 'source')"
RUN R -e "install.packages('panc8.SeuratData_3.0.2.tar.gz', repos = NULL, type = 'source')"
RUN R -e "install.packages('pbmcsca.SeuratData_3.0.0.tar.gz', repos = NULL, type = 'source')"
RUN R -e "install.packages('pbmc3k.SeuratData_3.0.0.tar.gz', repos = NULL, type = 'source')"
RUN rm ifnb.SeuratData_3.1.0.tar.gz panc8.SeuratData_3.0.2.tar.gz pbmcsca.SeuratData_3.0.0.tar.gz pbmc3k.SeuratData_3.0.0.tar.gz

# SCCAF
RUN python -m venv sccaf-venv \
    && . sccaf-venv/bin/activate \
    && pip install sccaf
ENV PATH $PATH:/opt/sccaf-venv/bin/

## scCATCH
RUN R -e "devtools::install_github('ZJUFanLab/scCATCH')"

# pySCENIC
RUN python -m venv pyscenic-venv \
    && . pyscenic-venv/bin/activate \
    && pip install pyscenic
ENV PATH $PATH:/opt/pyscenic-venv/bin/

## scAI
RUN R -e "devtools::install_github('sqjin/scAI')"

## Signac
RUN R -e "install.packages('Signac')" \
    && R -e "BiocManager::install(c('EnsDb.Hsapiens.v75', 'EnsDb.Mmusculus.v79','JASPAR2018'))"
