### Single-cell analysis pipeline for "Integrated analysis and regulation of cellular diversity"
# Installed tools: Seurat, Monocle2/3, Garnett, scater, scImpute, velocyto, scanpy, sleepwalk, liger, RCA, scBio, SCENIC, singleCellHaystack, scmap, scran, slingshot, CellPhoneDB, kallisto, BUSpaRse, bustools, scTensor
# cicero, chromVAR, archR

# splatter is an R script and cannot be installed by command
# https://github.com/MarioniLab/MNN2017/

FROM jupyter/datascience-notebook:1386e2046833

LABEL maintainer "Ryuichiro Nakato <rnakato@iam.u-tokyo.ac.jp>"

USER root
ENV PKG_CONFIG_PATH /opt/conda/lib/pkgconfig/:/usr/lib/x86_64-linux-gnu/pkgconfig/
ENV LD_LIBRARY_PATH /opt/conda/pkgs/r-base-3.6.1-h9bb98a2_1/lib/R/lib/
ENV PROJ_LIB /opt/conda/share/proj/

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    apt-file \
    apt-utils \
    build-essential \
    bzip2 \
    ca-certificates \
    cmake \
    curl \
    emacs \
    eog \
    evince \
    gawk \
    gedit \
    gfortran \
    git \
    gnupg \
    hdf5-helpers \
    htop \
    imagemagick \
    libblas-dev \
    libboost-all-dev \
    libbz2-dev \
    libcurl4-openssl-dev \
    libfreetype6-dev \
    libgdal-dev \
    libglu1-mesa-dev \
    libhdf5-dev \
    liblapack3 \
    liblapack-dev \
    libssl-dev \
    libudunits2-dev \
    libx11-dev \
    make \
    openjdk-8-jdk-headless \
    openjdk-8-jre \
    pigz \
    samtools \
    software-properties-common \
    sra-toolkit \
    unzip \
    vim \
    xorg \
    zlib1g-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN add-apt-repository ppa:ubuntugis/ubuntugis-unstable \
    && apt-get update \
    && apt-get install -y --no-install-recommends libudunits2-dev libgdal-dev libgeos-dev libproj-dev

RUN ln -s /usr/lib/x86_64-linux-gnu/libhdf5_serial.so.100 /usr/lib/x86_64-linux-gnu/libhdf5.so.100 \
    && ln -s /usr/lib/x86_64-linux-gnu/libhdf5_serial_hl.so.100 /usr/lib/x86_64-linux-gnu/libhdf5_hl.so.100

# Python
RUN conda install numpy numpy_groupies scipy pandas==0.23.4 cython numba matplotlib scikit-learn h5py click python-igraph louvain umap-learn \
    && conda install -c bioconda scanpy kallisto \
    && pip install -U velocyto cellphonedb

# R
RUN R -e "install.packages(c('Rcpp','devtools','BiocManager','igraph','sleepwalk','bit64','zoo','hdf5r'), repos='https://cran.ism.ac.jp/')"

# foreign CRAN package for R3.6.1 (older version)
RUN wget https://cran.r-project.org/src/contrib/Archive/foreign/foreign_0.8-74.tar.gz \
    && R CMD INSTALL foreign_0.8-74.tar.gz \
    && rm foreign_0.8-74.tar.gz

# Monocle3
RUN R -e "BiocManager::install(c('BiocGenerics', 'DelayedArray', 'DelayedMatrixStats', 'limma', 'S4Vectors', 'SingleCellExperiment', 'SummarizedExperiment', 'batchelor'))" \
    && R -e "devtools::install_github('cole-trapnell-lab/leidenbase')"

RUN conda install r-units r-sf gdal
RUN R -e "install.packages('curl', configure.vars='INCLUDE_DIR=/opt/conda/lib/pkgconfig/ LIB_DIR=/opt/conda/lib/pkgconfig/', repos='https://cran.ism.ac.jp/')" \
    && R -e "install.packages('units', configure.args='--with-udunits2-lib=/usr/lib/x86_64-linux-gnu/', repos='https://cran.ism.ac.jp/')" \
    && R -e "install.packages('sf', repos='https://cran.ism.ac.jp/')" \
    && R -e "devtools::install_github('cole-trapnell-lab/monocle3', ref='develop')" \
    && R -e "BiocManager::install(c('org.Mm.eg.db', 'org.Hs.eg.db', 'org.Dm.eg.db', 'org.Ce.eg.db'))" \
    && R -e "devtools::install_github('cole-trapnell-lab/garnett', ref='monocle3')"

RUN ln -s /bin/tar /bin/gtar \
    && R -e "BiocManager::install(c('limma', 'Seurat','scater','tsne','Rtsne','pcaMethods','WGCNA','preprocessCore', 'RCA', 'scmap', 'mixtools', 'rbokeh', 'DT', 'NMF', 'pheatmap', 'R2HTML', 'doMC', 'doRNG', 'scran', 'slingshot','DropletUtils','SingleR', 'monocle', 'scTensor','chromVAR'))" \
    && R -e "install.packages(c('scBio'), repos='https://cran.ism.ac.jp/')"
RUN R -e "devtools::install_github('aertslab/SCopeLoomR')" \
    && R -e "devtools::install_github('Vivianstats/scImpute')" \
    && R -e "devtools::install_github('alexisvdb/singleCellHaystack')"

# liger (FFTW, FIt-SNE)
RUN wget http://www.fftw.org/fftw-3.3.8.tar.gz \
    && tar zxvf fftw-3.3.8.tar.gz \
    && rm fftw-3.3.8.tar.gz \
    && cd fftw-3.3.8 \
    && ./configure \
    && make \
    && make install \
    && git clone https://github.com/KlugerLab/FIt-SNE.git \
    && cd FIt-SNE/ \
    && g++ -std=c++11 -O3  src/sptree.cpp src/tsne.cpp src/nbodyfft.cpp  -o bin/fast_tsne -pthread -lfftw3 -lm \
    && cp bin/fast_tsne /usr/local/bin/ \
    && rm -rf /home/jovyan/fftw-3.3.8
RUN R -e "devtools::install_github('MacoskoLab/liger')"

# velocyto
RUN conda install -c statiskit libboost \
    && R -e "devtools::install_github('velocyto-team/velocyto.R')"

RUN R -e "install.packages(c('stringi'), repos='https://cran.ism.ac.jp/')"

# kallisto, bustools
RUN git clone https://github.com/BUStools/bustools.git \
    && cd bustools \
    && mkdir build \
    && cd build \
    && cmake .. && make && make install \
    && R -e "devtools::install_github(c('tidymodels/tidymodels','BUStools/BUSpaRse'))" \
    && rm -rf /home/jovyan/bustools

# cicero
RUN R -e "devtools::install_github('cole-trapnell-lab/cicero-release', ref = 'monocle3')"

RUN R -e "devtools::install_github('GreenleafLab/ArchR', ref='master', repos = BiocManager::repositories())"

# permission of work/
RUN chmod -R 775 /home/jovyan/work

ENV CONF /home/jovyan/.jupyter/jupyter_notebook_config.py
ADD conf conf
RUN cat ./conf >> /home/jovyan/.jupyter/jupyter_notebook_config.py \
    && rm ./conf

USER jovyan
