FROM rnakato/r_python_gpu:2023.08
LABEL maintainer "Ryuichiro Nakato <rnakato@iqb.u-tokyo.ac.jp>"

USER root
WORKDIR /opt

SHELL ["/bin/bash", "-c"]

RUN set -x \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
    libarchive-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Dictys
RUN set -e \
    && conda create -y -n dictys -c conda-forge python=3.9 mamba jupyter notebook ipykernel seaborn \
    && source activate dictys \
    && conda install --channel conda-forge --channel bioconda pybedtools \
    && mamba install -y -c lingfeiwang -c bioconda -c conda-forge -c pytorch -c nvidia dictys pytorch torchvision torchaudio pytorch-cuda=11.7 \
    && python -m ipykernel install --name=dictys \
    && jupyter kernelspec list \
    && conda deactivate

### Final setting
RUN conda clean --all -y && pip cache purge
COPY run_env.sh /opt/scripts/run_env.sh
RUN chmod +x /opt/scripts/run_env.sh

ENV PATH $PATH:/opt:/opt/scripts

CMD ["/bin/bash"]
