### Single-cell analysis pipeline for "Integrated analysis and regulation of cellular diversity"
# Installed tools: Seurat, Monocle3, scater, scImpute, velocyto, scanpy, sleepwalk, liger, RCA, scBio, SCENIC, singleCellHaystack, scmap, scran, slingshot
# ArchR

# splatter is an R script and cannot be installed by command
# https://github.com/MarioniLab/MNN2017/
#pyscenic

FROM rnakato/r_python:r40u20
LABEL maintainer "Ryuichiro Nakato <rnakato@iam.u-tokyo.ac.jp>"

USER root
WORKDIR /opt

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    bat \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN  R -e "install.packages(c('sleepwalk','bit64','zoo','scBio','Seurat'), repos='https://cran.ism.ac.jp/')" \
     && R -e "BiocManager::install(c('limma','scater','pcaMethods','WGCNA','preprocessCore', 'RCA', 'scmap', 'mixtools', 'stringi', 'rbokeh', 'DT', 'NMF', 'pheatmap', 'R2HTML', 'doMC', 'doRNG', 'scran', 'slingshot'))" \
    && R -e "devtools::install_github(c('Vivianstats/scImpute', 'alexisvdb/singleCellHaystack', 'MacoskoLab/liger', 'velocyto-team/velocyto.R'))"
# , 'aertslab/SCopeLoomR': igraphがR4.0入らないためout

RUN R -e "install.packages(c('scBio','Seurat'), repos='https://cran.ism.ac.jp/')"
RUN R -e "devtools::install_github('GreenleafLab/ArchR', ref='master', repos = BiocManager::repositories())"

# Python
RUN conda install -y -c bioconda samtools scanpy \
    && conda install -y -c statiskit libboost \
    && pip install -U velocyto

# FFTW, FIt-SNE
RUN wget http://www.fftw.org/fftw-3.3.8.tar.gz \
    && tar zxvf fftw-3.3.8.tar.gz \
    && rm fftw-3.3.8.tar.gz \
    && cd fftw-3.3.8 \
    && ./configure \
    && make \
    && make install \
    && git clone https://github.com/KlugerLab/FIt-SNE.git \
    && cd FIt-SNE/ \
    && g++ -std=c++11 -O3  src/sptree.cpp src/tsne.cpp src/nbodyfft.cpp  -o bin/fast_tsne -pthread -lfftw3 -lm \
    && cp bin/fast_tsne /usr/local/bin/
