# syntax=docker/dockerfile:1
FROM rnakato/shortcake_r:3.5.0
LABEL maintainer="Ryuichiro Nakato <rnakato@iqb.u-tokyo.ac.jp>"

USER root
WORKDIR /opt
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    libgraphviz-dev \
    python-setuptools \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

### base
RUN pip install --no-cache-dir eeisp==0.5.0

### shortcake_default
COPY micromamba/env.shortcake_default.yaml /opt/env.shortcake_default.yaml
RUN eval "$(micromamba shell hook --shell bash)" \
    && micromamba create -y -n shortcake_default -f /opt/env.shortcake_default.yaml \
    && micromamba run -n shortcake_default pip install --no-cache-dir git+https://github.com/sfortma2/scranPY.git \
    && micromamba run -n shortcake_default python -m ipykernel install --name=shortcake_default \
    && micromamba run -n shortcake_default jupyter kernelspec list \
    && micromamba clean --all --yes \
    && rm /opt/env.shortcake_default.yaml

### squidpy
ENV ENVNAME=squidpy
RUN --mount=type=secret,id=github_pat,env=GITHUB_PAT \
    set -euo pipefail; \
    micromamba create -y -n $ENVNAME python=3.10 nbconvert==6.5.4 ipykernel==6.25.0 -c defaults \
    && micromamba run -n $ENVNAME pip install --no-cache-dir squidpy==1.6.2 napari==0.5.5 dask[array]==2024.11.2 session-info setuptools==80.10.2 \
    && micromamba run -n $ENVNAME python -m ipykernel install --name=$ENVNAME \
    && micromamba run -n $ENVNAME jupyter kernelspec list \
    && micromamba clean --all --yes \
# Salmon (Alevin)
    && cd /opt/ \
    && wget --progress=dot:giga https://github.com/COMBINE-lab/salmon/releases/download/v1.11.4/salmon-linux-x86_64.tar.gz \
    && tar zxvf salmon-linux-x86_64.tar.gz \
    && cp /opt/salmon-linux-x86_64/bin/salmon /usr/local/bin/ \
    && rm -rf salmon-linux-x86_64.tar.gz /opt/salmon-linux-x86_64

# SCENIC (pySCENIC)
#ENV ENVNAME=scenic
#RUN micromamba create -y -n $ENVNAME python=3.10 nbconvert ipykernel "numpy==1.23.5" -c conda-forge -c bioconda -c defaults \
#    && micromamba run -n $ENVNAME python -m ipykernel install --name=$ENVNAME \
#    && jupyter kernelspec list \
#    && micromamba clean --all --yes

# SCENIC+
ENV ENVNAME=scenic
RUN micromamba create -y -n $ENVNAME \
        python=3.11.8 pip wheel "poetry<2" macs2=2.2.9.1 \
        nbconvert ipykernel bedtools pybedtools cython "numpy==1.23.5" "pandas==1.5.3" "pyranges==0.0.111" "cython<3" \
        python-igraph louvain multicore-tsne ipywidgets pycistarget \
        -c conda-forge -c bioconda -c defaults \
    && micromamba run -n $ENVNAME pip install --no-build-isolation git+https://github.com/aertslab/LoomXpy@main \
    && micromamba run -n $ENVNAME pip install --no-build-isolation git+https://github.com/aertslab/pycisTopic.git \
    && micromamba run -n $ENVNAME pip install --no-cache-dir --no-deps "pyscenic==0.12.1" \
    && git clone https://github.com/aertslab/scenicplus \
    && cd scenicplus \
    && micromamba run -n $ENVNAME pip install --no-build-isolation --no-deps . \
    && micromamba run -n $ENVNAME pip install --no-cache-dir --no-deps "loomxpy==0.4.2" "numpy==1.23.5" setuptools==80.10.2 \
    && micromamba run -n $ENVNAME python -m ipykernel install --name=$ENVNAME \
    && jupyter kernelspec list \
    && micromamba clean --all --yes

### Final setting
COPY run_env.sh /opt/scripts/run_env.sh
RUN chmod +x /opt/scripts/run_env.sh

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh \
    && mkdir -p /.singularity.d \
    && echo '#!/bin/sh\n. /entrypoint.sh\nexec "$@"' > /.singularity.d/runscript \
    && chmod +x /.singularity.d/runscript

ENV LD_LIBRARY_PATH=/opt/micromamba/envs/shortcake_default/lib:$LD_LIBRARY_PATH
ENV GITHUB_PAT=
ENV PATH=$PATH:/opt:/opt/scripts:
ENTRYPOINT ["/entrypoint.sh"]

CMD ["/bin/bash"]
