#!/usr/bin/env bash
# AUTO-GENERATED by generate_testrun.py
# Do not edit this file directly.
set -u

TAG="${1:-${TAG:-3.5.0}}"
SHORTCAKE_TTY="${SHORTCAKE_TTY:-0}"
DOCKER_EXTRA_ARGS="${DOCKER_EXTRA_ARGS:-}"

TOTAL=0
FAILURES=0
FAILED_LABELS=()

if [[ "$SHORTCAKE_TTY" == "1" ]]; then
    DOCKER_TTY_ARGS=(-it)
else
    DOCKER_TTY_ARGS=()
fi

run_check() {
    local label="$1"
    local image="$2"
    local envname="$3"
    local gpu="$4"
    local inner_cmd="$5"

    TOTAL=$((TOTAL + 1))
    echo
    echo "================================================================"
    echo "[${TOTAL}] $label"
    echo "================================================================"

    local -a cmd=(docker run "${DOCKER_TTY_ARGS[@]}" --rm)
    if [[ -n "$DOCKER_EXTRA_ARGS" ]]; then
        # shellcheck disable=SC2206
        cmd+=($DOCKER_EXTRA_ARGS)
    fi
    if [[ "$gpu" == "1" ]]; then
        cmd+=(--gpus all)
    fi
    cmd+=("${image}:${TAG}")

    if [[ -n "$envname" ]]; then
        cmd+=(run_env.sh "$envname" bash -lc "$inner_cmd")
    else
        cmd+=(bash -lc "$inner_cmd")
    fi

    printf '+ '
    printf '%q ' "${cmd[@]}"
    echo

    if "${cmd[@]}"; then
        echo "OK: $label"
    else
        local status=$?
        echo "FAILED($status): $label" >&2
        FAILURES=$((FAILURES + 1))
        FAILED_LABELS+=("$label")
    fi
}

run_import() {
    local label="$1"
    local image="$2"
    local envname="$3"
    local module="$4"
    local print_version="$5"
    local gpu="$6"

    local pycmd
    if [[ "$print_version" == "1" ]]; then
        pycmd="import importlib; m=importlib.import_module('${module}'); print(getattr(m, '__version__', 'NO_VERSION_ATTR'))"
    else
        pycmd="import importlib; importlib.import_module('${module}'); print('IMPORTED')"
    fi

    local inner_cmd
    inner_cmd="python -c $(printf '%q' "$pycmd")"
    run_check "$label" "$image" "$envname" "$gpu" "$inner_cmd"
}

run_cli() {
    local label="$1"
    local image="$2"
    local envname="$3"
    local gpu="$4"
    local cli_cmd="$5"
    run_check "$label" "$image" "$envname" "$gpu" "$cli_cmd"
}

# light / shortcake_default
run_import 'shortcake_light / shortcake_default / import autogenes' rnakato/shortcake_light shortcake_default autogenes 1 0
run_import 'shortcake_light / shortcake_default / import bbknn' rnakato/shortcake_light shortcake_default bbknn 1 0
run_import 'shortcake_light / shortcake_default / import cellmap' rnakato/shortcake_light shortcake_default cellmap 1 0
run_import 'shortcake_light / shortcake_default / import celltypist' rnakato/shortcake_light shortcake_default celltypist 1 0
run_import 'shortcake_light / shortcake_default / import cellrank' rnakato/shortcake_light shortcake_default cellrank 1 0
run_import 'shortcake_light / shortcake_default / import constclust' rnakato/shortcake_light shortcake_default constclust 1 0
run_import 'shortcake_light / shortcake_default / import cython' rnakato/shortcake_light shortcake_default cython 1 0
run_import 'shortcake_light / shortcake_default / import dask' rnakato/shortcake_light shortcake_default dask 1 0
run_import 'shortcake_light / shortcake_default / import doubletdetection' rnakato/shortcake_light shortcake_default doubletdetection 1 0
run_import 'shortcake_light / shortcake_default / import harmonypy' rnakato/shortcake_light shortcake_default harmonypy 1 0
run_import 'shortcake_light / shortcake_default / import llvmlite' rnakato/shortcake_light shortcake_default llvmlite 1 0
run_import 'shortcake_light / shortcake_default / import louvain' rnakato/shortcake_light shortcake_default louvain 1 0
run_import 'shortcake_light / shortcake_default / import leidenalg' rnakato/shortcake_light shortcake_default leidenalg 1 0
run_import 'shortcake_light / shortcake_default / import magic' rnakato/shortcake_light shortcake_default magic 1 0
run_import 'shortcake_light / shortcake_default / import memento' rnakato/shortcake_light shortcake_default memento 1 0
run_import 'shortcake_light / shortcake_default / import multivelo' rnakato/shortcake_light shortcake_default multivelo 1 0
run_import 'shortcake_light / shortcake_default / import numba' rnakato/shortcake_light shortcake_default numba 1 0
run_import 'shortcake_light / shortcake_default / import optuna' rnakato/shortcake_light shortcake_default optuna 1 0
run_import 'shortcake_light / shortcake_default / import palantir' rnakato/shortcake_light shortcake_default palantir 1 0
run_import 'shortcake_light / shortcake_default / import phenograph' rnakato/shortcake_light shortcake_default phenograph 1 0
run_import 'shortcake_light / shortcake_default / import phate' rnakato/shortcake_light shortcake_default phate 1 0
run_import 'shortcake_light / shortcake_default / import scanorama' rnakato/shortcake_light shortcake_default scanorama 1 0
run_import 'shortcake_light / shortcake_default / import scib' rnakato/shortcake_light shortcake_default scib 1 0
run_import 'shortcake_light / shortcake_default / import scanpy' rnakato/shortcake_light shortcake_default scanpy 1 0
run_import 'shortcake_light / shortcake_default / import screcode' rnakato/shortcake_light shortcake_default screcode 1 0
run_import 'shortcake_light / shortcake_default / import scrublet' rnakato/shortcake_light shortcake_default scrublet 1 0
run_import 'shortcake_light / shortcake_default / import scvelo' rnakato/shortcake_light shortcake_default scvelo 1 0
run_import 'shortcake_light / shortcake_default / import snapatac2' rnakato/shortcake_light shortcake_default snapatac2 1 0
run_import 'shortcake_light / shortcake_default / import velocyto' rnakato/shortcake_light shortcake_default velocyto 1 0

# light / scenic
run_import 'shortcake_light / scenic / import scanpy' rnakato/shortcake_light scenic scanpy 1 0
run_import 'shortcake_light / scenic / import loompy' rnakato/shortcake_light scenic loompy 1 0
run_import 'shortcake_light / scenic / import pyscenic' rnakato/shortcake_light scenic pyscenic 1 0

# light / squidpy
run_import 'shortcake_light / squidpy / import squidpy' rnakato/shortcake_light squidpy squidpy 1 0

# default / per-tool envs
run_import 'shortcake / celloracle / import celloracle' rnakato/shortcake celloracle celloracle 1 0
run_import 'shortcake / cellphonedb / import cellphonedb' rnakato/shortcake cellphonedb cellphonedb 1 0
run_import 'shortcake / episcanpy / import episcanpy' rnakato/shortcake episcanpy episcanpy 1 0
run_import 'shortcake / mario / import mario' rnakato/shortcake mario mario 1 0
run_import 'shortcake / genes2genes-mowgli / import genes2genes' rnakato/shortcake genes2genes-mowgli genes2genes 1 0
run_import 'shortcake / genes2genes-mowgli / import mowgli' rnakato/shortcake genes2genes-mowgli mowgli 1 0
run_import 'shortcake / dynamo / import dynamo' rnakato/shortcake dynamo dynamo 1 0
run_import 'shortcake / moscot / import moscot' rnakato/shortcake moscot moscot 1 0
run_import 'shortcake / cell2cell-screadsim / import cell2cell' rnakato/shortcake cell2cell-screadsim cell2cell 1 0
run_import 'shortcake / cell2cell-screadsim / import scReadSim' rnakato/shortcake cell2cell-screadsim scReadSim 1 0
run_import 'shortcake / decoupler-liana-sctriangulate / import decoupler' rnakato/shortcake decoupler-liana-sctriangulate decoupler 1 0
run_import 'shortcake / decoupler-liana-sctriangulate / import liana' rnakato/shortcake decoupler-liana-sctriangulate liana 1 0
run_import 'shortcake / decoupler-liana-sctriangulate / import sctriangulate' rnakato/shortcake decoupler-liana-sctriangulate sctriangulate 1 0
run_import 'shortcake / ikarus-novosparc / import ikarus' rnakato/shortcake ikarus-novosparc ikarus 1 0
run_import 'shortcake / ikarus-novosparc / import novosparc' rnakato/shortcake ikarus-novosparc novosparc 1 0
run_import 'shortcake / seacells / import SEACells' rnakato/shortcake seacells SEACells 0 0

# full / GPU envs
run_import 'shortcake_full / dictys / import dictys' rnakato/shortcake_full dictys dictys 1 1
run_import 'shortcake_full / gears / import gears' rnakato/shortcake_full gears gears 1 1
run_import 'shortcake_full / rapids_singlecell / import rapids_singlecell' rnakato/shortcake_full rapids_singlecell rapids_singlecell 1 1
run_import 'shortcake_full / scvi-scgen-scmomat-unitvelo / import scvi' rnakato/shortcake_full scvi-scgen-scmomat-unitvelo scvi 1 1
run_import 'shortcake_full / scvi-scgen-scmomat-unitvelo / import scgen' rnakato/shortcake_full scvi-scgen-scmomat-unitvelo scgen 1 1
run_import 'shortcake_full / scvi-scgen-scmomat-unitvelo / import scmomat' rnakato/shortcake_full scvi-scgen-scmomat-unitvelo scmomat 1 1
run_import 'shortcake_full / scvi-scgen-scmomat-unitvelo / import unitvelo' rnakato/shortcake_full scvi-scgen-scmomat-unitvelo unitvelo 1 1

# scvi flavor / GPU envs
run_import 'shortcake_scvi / scvi-scgen-scmomat-unitvelo / import scvi' rnakato/shortcake_scvi scvi-scgen-scmomat-unitvelo scvi 1 1
run_import 'shortcake_scvi / scvi-scgen-scmomat-unitvelo / import scgen' rnakato/shortcake_scvi scvi-scgen-scmomat-unitvelo scgen 1 1
run_import 'shortcake_scvi / scvi-scgen-scmomat-unitvelo / import scmomat' rnakato/shortcake_scvi scvi-scgen-scmomat-unitvelo scmomat 1 1
run_import 'shortcake_scvi / scvi-scgen-scmomat-unitvelo / import unitvelo' rnakato/shortcake_scvi scvi-scgen-scmomat-unitvelo unitvelo 1 1

# rapidsc flavor / GPU envs
run_import 'shortcake_rapidsc / rapids_singlecell / import rapids_singlecell' rnakato/shortcake_rapidsc rapids_singlecell rapids_singlecell 1 1

# CLI checks
run_cli 'light / scenic cli / pyscenic' rnakato/shortcake_light scenic 0 pyscenic
run_cli 'light / scenic cli / scenicplus' rnakato/shortcake_light scenic 0 scenicplus
run_cli 'default / cli / eeisp --version' rnakato/shortcake '' 0 'eeisp --version'
run_cli 'full / stellar smoke' rnakato/shortcake_full stellar 0 'python /opt/stellar/STELLAR_run.py'
echo
echo "================================================================"
echo "Summary"
echo "================================================================"
echo "Total checks : $TOTAL"
echo "Failures     : $FAILURES"

if [[ "$FAILURES" -gt 0 ]]; then
    echo
    echo "Failed labels:"
    printf '  - %s
' "${FAILED_LABELS[@]}"
    exit 1
fi

echo "All checks passed."
